'***********************************************************************************************************************
'* Project: CmisObjectModelLibrary
'* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
'*
'* Contact: opensource<at>patorg.de
'* 
'* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
'*
'* This file is part of CmisObjectModelLibrary.
'* 
'* This library is free software; you can redistribute it and/or
'* modify it under the terms of the GNU Lesser General Public
'* License as published by the Free Software Foundation; either
'* version 3.0 of the License, or (at your option) any later version.
'*
'* This library is distributed in the hope that it will be useful,
'* but WITHOUT ANY WARRANTY; without even the implied warranty of
'* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
'* Lesser General Public License for more details.
'*
'* You should have received a copy of the GNU Lesser General Public
'* License along with this library (lgpl.txt).
'* If not, see <http://www.gnu.org/licenses/lgpl.txt>.
'***********************************************************************************************************************
Imports cc = CmisObjectModel.Core
Imports ccc = CmisObjectModel.Core.Choices
Imports ccdp = CmisObjectModel.Core.Definitions.Properties
Imports ccdt = CmisObjectModel.Core.Definitions.Types
Imports ccp = CmisObjectModel.Core.Properties
Imports ccs = CmisObjectModel.Core.Security
Imports cjc = CmisObjectModel.JSON.Core
Imports cjccg = CmisObjectModel.JSON.Core.Choices.Generic
Imports cjcp = CmisObjectModel.JSON.Core.Properties
Imports cjcdp = CmisObjectModel.JSON.Core.Definitions.Properties
Imports cjcdpg = CmisObjectModel.JSON.Core.Definitions.Properties.Generic
Imports cjcdt = CmisObjectModel.JSON.Core.Definitions.Types
Imports cjcdtg = CmisObjectModel.JSON.Core.Definitions.Types.Generic
Imports cjcs = CmisObjectModel.JSON.Core.Security
Imports cjm = CmisObjectModel.JSON.Messaging
Imports cjs = CmisObjectModel.JSON.Serialization
Imports cm = CmisObjectModel.Messaging
Imports cmr = CmisObjectModel.Messaging.Responses

#If xs_Integer = "Int32" OrElse xs_integer = "Integer" OrElse xs_integer = "Single" Then
Imports xs_Integer = System.Int32
#Else
Imports xs_Integer = System.Int64
#End If

Namespace CmisObjectModel.Constants
   <HideModuleName()>
   Public Module JSONConstants
      Public Const jsFrameUri As String = "b1dd0f15138a41d5994a2df00b7f2816"
      Public Const jsLoginKeyCookie As String = "a4b2726d8a59435b85527a833cfe194c"
      Public Const jsLoginUri As String = "a00ca801b5714a2989b001a3ad924c53"
      Public Const jsHostingApplicationUri As String = "820972d652e34dfc8b730fd64dc1ca74"
      Public Const jsRepositoryDomain As String = "6352c757d11f45d7b7408a2e468ce249"
      Public Const jsServiceUri As String = "5f2bd79dc36843c6a0794545f9c5350d"
      Public Const jsSessionIdCookie As String = "63d92532245a4c8998c095ac30d33690"
   End Module

   ''' <summary>
   ''' Maps JSON-typedefinitions to real classes in CmisObjectModelLibrary
   ''' </summary>
   ''' <remarks></remarks>
   Public MustInherit Class JSONTypeDefinitions
      Private Sub New()
      End Sub

#Region "Helper classes"
      ''' <summary>
      ''' Defines the correlation between the JSONTypeDefinition and the type representation defined in this assembly
      ''' </summary>
      ''' <remarks></remarks>
      Public Class RealTypeCorrelation
         Public Sub New(jsonTypeDefinitionName As String, representationType As Type)
            Dim javaScriptConverterAttr As Attributes.JavaScriptConverterAttribute =
               cjs.JavaScriptSerializer.GetCustomAttribute(Of Attributes.JavaScriptConverterAttribute)(representationType)
            If javaScriptConverterAttr IsNot Nothing Then Me.ConverterType = javaScriptConverterAttr.JavaScriptConverterType(representationType)
            Me.IsAutoGenerated = True
            Me.JSONTypeDefinitionName = jsonTypeDefinitionName
            Me.RepresentationType = representationType
         End Sub
         Public Sub New(jsonTypeDefinitionName As String, representationType As Type, converterType As Type)
            Me.ConverterType = converterType
            Me.IsAutoGenerated = False
            Me.JSONTypeDefinitionName = jsonTypeDefinitionName
            Me.RepresentationType = representationType
         End Sub

         Public ReadOnly ConverterType As Type
         Public ReadOnly IsAutoGenerated As Boolean
         Public ReadOnly JSONTypeDefinitionName As String
         Public ReadOnly RepresentationType As Type
      End Class
#End Region

#Region "Constants"
      Public Const aceUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ace"
      Public Const aclUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/acl"
      Public Const aclCapabilitiesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ACLcapabilities"
      Public Const allowableActionsUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/allowableActions"
      Public Const capabilityCreatablePropertyTypesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/capabilityCreatablePropertyTypes"
      Public Const capabilityNewTypeSettableAttributesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/capabilityNewTypeSettableAttributes"
      Public Const changeEventUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/changeEvent"
      Public Const choiceBooleanUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceBoolean"
      Public Const choiceDateTimeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceDateTime"
      Public Const choiceDecimalUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceDecimal"
      Public Const choiceHtmlUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceHtml"
      Public Const choiceIdUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceId"
      Public Const choiceIntegerUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceInteger"
      Public Const choiceStringUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceString"
      Public Const choiceUriUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ChoiceUri"
      Public Const extendedFeaturesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/extendedFeatures"
      Public Const idsUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/ids"
      Public Const objectUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/object"
      Public Const objectContainerUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/objectContainer"
      Public Const objectIdAndChangeTokenUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/objectIdAndChangeToken"
      Public Const objectInFolderUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/objectInFolder"
      Public Const objectInFolderListUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/objectInFolderList"
      Public Const objectListUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/objectList"
      Public Const objectParentUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/objectParent"
      Public Const permissionDefinitionUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/permissionDefinition"
      Public Const permissionMappingUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/permissionMapping"
      Public Const propertiesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/properties"
      Public Const propertiesExtensionUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertiesExtension"
      Public Const propertyBooleanUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyBoolean"
      Public Const propertyBooleanDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyBooleanDefinitionType"
      Public Const propertyDateTimeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyDateTime"
      Public Const propertyDateTimeDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyDateTimeDefinitionType"
      Public Const propertyDecimalUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyDecimal"
      Public Const propertyDecimalDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyDecimalDefinitionType"
      Public Const propertyDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyDefinitionType"
      Public Const propertyHtmlUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyHtml"
      Public Const propertyHtmlDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyHtmlDefinitionType"
      Public Const propertyIdUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyId"
      Public Const propertyIdDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyIdDefinitionType"
      Public Const propertyIntegerUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyInteger"
      Public Const propertyIntegerDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyIntegerDefinitionType"
      Public Const propertyStringUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyString"
      Public Const propertyStringDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyStringDefinitionType"
      Public Const propertyUriUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyUri"
      Public Const propertyUriDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/propertyUriDefinitionType"
      Public Const queryPropertiesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/queryProperties"
      Public Const queryPropertyUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/queryProperty"
      Public Const queryResultUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/queryResult"
      Public Const queryResultListUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/queryResultList"
      Public Const renditionUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/rendition"
      Public Const repositoriesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/repositories"
      Public Const repositoryCapabilitiesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/repositoryCapabilities"
      Public Const repositoryInfoUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/repositoryInfo"
      Public Const succinctPropertiesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/succinctProperties"
      Public Const succinctQueryPropertiesUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/succinctQueryProperties"
      Public Const transactionUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/transaction"
      Public Const typeContainerUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeContainer"
      Public Const typeDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeDefinitionType"
      Public Const typeDocumentDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeDocumentDefinitionType"
      Public Const typeFolderDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeFolderDefinitionType"
      Public Const typeItemDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeItemDefinitionType"
      Public Const typeListUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeList"
      Public Const typeMutabilityUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeMutability"
      Public Const typePolicyDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typePolicyDefinitionType"
      Public Const typeRelationshipDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeRelationshipDefinitionType"
      Public Const typeRM_ClientMgtRetentionDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeRM_ClientMgtRetentionDefinitionType"
      Public Const typeRM_DestructionRetentionDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeRM_DestructionRetentionDefinitionType"
      Public Const typeRM_HoldDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeRM_HoldDefinitionType"
      Public Const typeRM_RepMgtRetentionDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeRM_RepMgtRetentionDefinitionType"
      Public Const typeSecondaryDefinitionTypeUri As String = "http://docs.oasis-open.org/ns/cmis/browser/201103/typeSecondaryDefinitionType"
#End Region

      Public Shared ReadOnly RepresentationTypes As New Dictionary(Of String, RealTypeCorrelation) From {
         {aceUri, New RealTypeCorrelation(aceUri,
                                          GetType(ccs.cmisAccessControlEntryType),
                                          GetType(cjcs.cmisAccessControlEntryTypeConverter))},
         {aclUri, New RealTypeCorrelation(aclUri,
                                          GetType(ccs.cmisAccessControlListType),
                                          GetType(cjcs.cmisAccessControlListTypeConverter))},
         {aclCapabilitiesUri, New RealTypeCorrelation(aclCapabilitiesUri, GetType(ccs.cmisACLCapabilityType))},
         {allowableActionsUri, New RealTypeCorrelation(allowableActionsUri, GetType(cc.cmisAllowableActionsType))},
         {capabilityCreatablePropertyTypesUri, New RealTypeCorrelation(capabilityCreatablePropertyTypesUri, GetType(cc.cmisCreatablePropertyTypesType))},
         {capabilityNewTypeSettableAttributesUri, New RealTypeCorrelation(capabilityNewTypeSettableAttributesUri, GetType(cc.cmisNewTypeSettableAttributes))},
         {changeEventUri, New RealTypeCorrelation(changeEventUri, GetType(cc.cmisChangeEventType))},
         {choiceBooleanUri, New RealTypeCorrelation(choiceBooleanUri,
                                                    GetType(ccc.cmisChoiceBoolean),
                                                    GetType(cjccg.cmisChoiceConverter(Of Boolean, ccc.cmisChoiceBoolean)))},
         {choiceDateTimeUri, New RealTypeCorrelation(choiceDateTimeUri,
                                                     GetType(ccc.cmisChoiceDateTime),
                                                     GetType(cjccg.cmisChoiceConverter(Of DateTimeOffset, ccc.cmisChoiceDateTime)))},
         {choiceDecimalUri, New RealTypeCorrelation(choiceDecimalUri,
                                                    GetType(ccc.cmisChoiceDecimal),
                                                    GetType(cjccg.cmisChoiceConverter(Of Decimal, ccc.cmisChoiceDecimal)))},
         {choiceHtmlUri, New RealTypeCorrelation(choiceHtmlUri,
                                                 GetType(ccc.cmisChoiceHtml),
                                                 GetType(cjccg.cmisChoiceConverter(Of String, ccc.cmisChoiceHtml)))},
         {choiceIdUri, New RealTypeCorrelation(choiceIdUri,
                                               GetType(ccc.cmisChoiceId),
                                               GetType(cjccg.cmisChoiceConverter(Of String, ccc.cmisChoiceId)))},
         {choiceIntegerUri, New RealTypeCorrelation(choiceIntegerUri,
                                                    GetType(ccc.cmisChoiceInteger),
                                                    GetType(cjccg.cmisChoiceConverter(Of xs_Integer, ccc.cmisChoiceInteger)))},
         {choiceStringUri, New RealTypeCorrelation(choiceStringUri,
                                                   GetType(ccc.cmisChoiceString),
                                                   GetType(cjccg.cmisChoiceConverter(Of String, ccc.cmisChoiceString)))},
         {choiceUriUri, New RealTypeCorrelation(choiceUriUri,
                                                GetType(ccc.cmisChoiceUri),
                                                GetType(cjccg.cmisChoiceConverter(Of String, ccc.cmisChoiceUri)))},
         {extendedFeaturesUri, New RealTypeCorrelation(extendedFeaturesUri,
                                                       GetType(cc.cmisExtensionFeatureType),
                                                       GetType(cjc.cmisExtensionFeatureTypeConverter))},
         {idsUri, New RealTypeCorrelation(idsUri, GetType(cc.Collections.cmisListOfIdsType))},
         {objectUri, New RealTypeCorrelation(objectUri, GetType(cc.cmisObjectType))},
         {objectContainerUri, New RealTypeCorrelation(objectContainerUri, GetType(cm.cmisObjectInFolderContainerType))},
         {objectIdAndChangeTokenUri, New RealTypeCorrelation(objectIdAndChangeTokenUri, GetType(cc.cmisObjectIdAndChangeTokenType))},
         {objectInFolderUri, New RealTypeCorrelation(objectInFolderUri, GetType(cm.cmisObjectInFolderType))},
         {objectInFolderListUri, New RealTypeCorrelation(objectInFolderListUri, GetType(cm.cmisObjectInFolderListType))},
         {objectListUri, New RealTypeCorrelation(objectListUri,
                                                 GetType(cmr.getContentChangesResponse),
                                                 GetType(cjm.ObjectListConverter))},
         {objectParentUri, New RealTypeCorrelation(objectParentUri, GetType(cm.cmisObjectParentsType))},
         {permissionDefinitionUri, New RealTypeCorrelation(permissionDefinitionUri, GetType(ccs.cmisPermissionDefinition))},
         {permissionMappingUri, New RealTypeCorrelation(permissionMappingUri, GetType(ccs.cmisPermissionMapping))},
         {propertiesUri, New RealTypeCorrelation(propertiesUri,
                                                 GetType(cc.Collections.cmisPropertiesType),
                                                 GetType(CmisObjectModel.JSON.Collections.PropertiesConverter))},
         {propertiesExtensionUri, New RealTypeCorrelation(propertiesExtensionUri,
                                                          GetType(cc.cmisObjectType.PropertiesExtensions),
                                                          GetType(cjc.cmisObjectTypeConverter.PropertiesExtensionsConverter))},
         {propertyBooleanUri, New RealTypeCorrelation(propertyBooleanUri,
                                                      GetType(ccp.cmisPropertyBoolean),
                                                      GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyBooleanDefinitionTypeUri, New RealTypeCorrelation(propertyBooleanDefinitionTypeUri,
                                                                    GetType(ccdp.cmisPropertyBooleanDefinitionType),
                                                                    GetType(cjcdpg.cmisPropertyDefinitionTypeConverter(Of Boolean, ccc.cmisChoiceBoolean,
                                                                                                                          ccp.cmisPropertyBoolean,
                                                                                                                          ccdp.cmisPropertyBooleanDefinitionType)))},
         {propertyDateTimeUri, New RealTypeCorrelation(propertyDateTimeUri,
                                                       GetType(ccp.cmisPropertyDateTime),
                                                       GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyDateTimeDefinitionTypeUri, New RealTypeCorrelation(propertyDateTimeDefinitionTypeUri,
                                                                     GetType(ccdp.cmisPropertyDateTimeDefinitionType),
                                                                     GetType(cjcdp.cmisPropertyDateTimeDefinitionTypeConverter))},
         {propertyDecimalUri, New RealTypeCorrelation(propertyDecimalUri,
                                                      GetType(ccp.cmisPropertyDecimal),
                                                      GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyDecimalDefinitionTypeUri, New RealTypeCorrelation(propertyDecimalDefinitionTypeUri,
                                                                    GetType(ccdp.cmisPropertyDecimalDefinitionType),
                                                                    GetType(cjcdp.cmisPropertyDecimalDefinitionTypeConverter))},
         {propertyDefinitionTypeUri, New RealTypeCorrelation(propertyDefinitionTypeUri,
                                                             GetType(ccdp.cmisPropertyDefinitionType),
                                                             GetType(cjcdp.cmisPropertyDefinitionTypeConverter))},
         {propertyHtmlUri, New RealTypeCorrelation(propertyHtmlUri,
                                                   GetType(ccp.cmisPropertyHtml),
                                                   GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyHtmlDefinitionTypeUri, New RealTypeCorrelation(propertyHtmlDefinitionTypeUri,
                                                                 GetType(ccdp.cmisPropertyHtmlDefinitionType),
                                                                 GetType(cjcdpg.cmisPropertyDefinitionTypeConverter(Of String, ccc.cmisChoiceHtml,
                                                                                                                       ccp.cmisPropertyHtml,
                                                                                                                       ccdp.cmisPropertyHtmlDefinitionType)))},
         {propertyIdUri, New RealTypeCorrelation(propertyIdUri,
                                                 GetType(ccp.cmisPropertyId),
                                                 GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyIdDefinitionTypeUri, New RealTypeCorrelation(propertyIdDefinitionTypeUri,
                                                               GetType(ccdp.cmisPropertyIdDefinitionType),
                                                               GetType(cjcdpg.cmisPropertyDefinitionTypeConverter(Of String, ccc.cmisChoiceId,
                                                                                                                     ccp.cmisPropertyId,
                                                                                                                     ccdp.cmisPropertyIdDefinitionType)))},
         {propertyIntegerUri, New RealTypeCorrelation(propertyIntegerUri,
                                                      GetType(ccp.cmisPropertyInteger),
                                                      GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyIntegerDefinitionTypeUri, New RealTypeCorrelation(propertyIntegerDefinitionTypeUri,
                                                                    GetType(ccdp.cmisPropertyIntegerDefinitionType),
                                                                    GetType(cjcdp.cmisPropertyIntegerDefinitionTypeConverter))},
         {propertyStringUri, New RealTypeCorrelation(propertyStringUri,
                                                     GetType(ccp.cmisPropertyString),
                                                     GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyStringDefinitionTypeUri, New RealTypeCorrelation(propertyStringDefinitionTypeUri,
                                                                   GetType(ccdp.cmisPropertyStringDefinitionType),
                                                                   GetType(cjcdp.cmisPropertyStringDefinitionTypeConverter))},
         {propertyUriUri, New RealTypeCorrelation(propertyUriUri,
                                                  GetType(ccp.cmisPropertyUri),
                                                  GetType(cjc.Properties.cmisPropertyConverter))},
         {propertyUriDefinitionTypeUri, New RealTypeCorrelation(propertyUriDefinitionTypeUri,
                                                                GetType(ccdp.cmisPropertyUriDefinitionType),
                                                                GetType(cjcdpg.cmisPropertyDefinitionTypeConverter(Of String, ccc.cmisChoiceUri,
                                                                                                                      ccp.cmisPropertyUri,
                                                                                                                      ccdp.cmisPropertyUriDefinitionType)))},
         {queryPropertiesUri, New RealTypeCorrelation(queryPropertiesUri,
                                                      GetType(cc.Collections.cmisPropertiesType),
                                                      GetType(CmisObjectModel.JSON.Collections.PropertiesConverter))},
         {queryPropertyUri, New RealTypeCorrelation(queryPropertyUri,
                                                    GetType(ccp.cmisProperty),
                                                    GetType(cjcp.QueryPropertyConverter))},
         {queryResultUri, New RealTypeCorrelation(queryResultUri,
                                                  GetType(cc.cmisObjectType),
                                                  GetType(cjc.QueryResultConverter))},
         {queryResultListUri, New RealTypeCorrelation(queryResultListUri,
                                                      GetType(cm.cmisObjectListType),
                                                      GetType(cjm.QueryResultListConverter))},
         {renditionUri, New RealTypeCorrelation(renditionUri, GetType(cc.cmisRenditionType))},
         {repositoriesUri, New RealTypeCorrelation(repositoriesUri,
                                                   GetType(cc.cmisRepositoryInfoType()),
                                                   Nothing)},
         {repositoryCapabilitiesUri, New RealTypeCorrelation(repositoryCapabilitiesUri, GetType(cc.cmisRepositoryCapabilitiesType))},
         {repositoryInfoUri, New RealTypeCorrelation(repositoryInfoUri, GetType(cc.cmisRepositoryInfoType))},
         {succinctPropertiesUri, New RealTypeCorrelation(succinctPropertiesUri,
                                                         GetType(cc.Collections.cmisPropertiesType),
                                                         GetType(CmisObjectModel.JSON.Collections.SuccinctPropertiesConverter))},
         {succinctQueryPropertiesUri, New RealTypeCorrelation(succinctQueryPropertiesUri,
                                                              GetType(cc.Collections.cmisPropertiesType),
                                                              GetType(CmisObjectModel.JSON.Collections.SuccinctPropertiesConverter))},
         {transactionUri, New RealTypeCorrelation(transactionUri,
                                                  GetType(CmisObjectModel.JSON.Transaction),
                                                  GetType(CmisObjectModel.JSON.TransactionConverter))},
         {typeContainerUri, New RealTypeCorrelation(typeContainerUri, GetType(cm.cmisTypeContainer))},
         {typeDefinitionTypeUri, New RealTypeCorrelation(typeDefinitionTypeUri,
                                                         GetType(ccdt.cmisTypeDefinitionType),
                                                         GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeDefinitionType)))},
         {typeDocumentDefinitionTypeUri, New RealTypeCorrelation(typeDocumentDefinitionTypeUri,
                                                                 GetType(ccdt.cmisTypeDocumentDefinitionType),
                                                                 GetType(cjcdt.cmisTypeDocumentDefinitionTypeConverter))},
         {typeFolderDefinitionTypeUri, New RealTypeCorrelation(typeFolderDefinitionTypeUri,
                                                               GetType(ccdt.cmisTypeFolderDefinitionType),
                                                               GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeFolderDefinitionType)))},
         {typeItemDefinitionTypeUri, New RealTypeCorrelation(typeItemDefinitionTypeUri,
                                                             GetType(ccdt.cmisTypeItemDefinitionType),
                                                             GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeItemDefinitionType)))},
         {typeListUri, New RealTypeCorrelation(typeListUri, GetType(cm.cmisTypeDefinitionListType))},
         {typeMutabilityUri, New RealTypeCorrelation(typeMutabilityUri, GetType(cc.cmisTypeMutabilityCapabilitiesType))},
         {typePolicyDefinitionTypeUri, New RealTypeCorrelation(typePolicyDefinitionTypeUri,
                                                               GetType(ccdt.cmisTypePolicyDefinitionType),
                                                               GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypePolicyDefinitionType)))},
         {typeRelationshipDefinitionTypeUri, New RealTypeCorrelation(typeRelationshipDefinitionTypeUri,
                                                                     GetType(ccdt.cmisTypeRelationshipDefinitionType),
                                                                     GetType(cjcdt.cmisTypeRelationshipDefinitionTypeConverter))},
         {typeRM_ClientMgtRetentionDefinitionTypeUri, New RealTypeCorrelation(typeRM_ClientMgtRetentionDefinitionTypeUri,
                                                               GetType(ccdt.cmisTypeRM_ClientMgtRetentionDefinitionType),
                                                               GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeRM_ClientMgtRetentionDefinitionType)))},
         {typeRM_DestructionRetentionDefinitionTypeUri, New RealTypeCorrelation(typeRM_DestructionRetentionDefinitionTypeUri,
                                                               GetType(ccdt.cmisTypeRM_DestructionRetentionDefinitionType),
                                                               GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeRM_DestructionRetentionDefinitionType)))},
         {typeRM_HoldDefinitionTypeUri, New RealTypeCorrelation(typeRM_HoldDefinitionTypeUri,
                                                               GetType(ccdt.cmisTypeRM_HoldDefinitionType),
                                                               GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeRM_HoldDefinitionType)))},
         {typeRM_RepMgtRetentionDefinitionTypeUri, New RealTypeCorrelation(typeRM_RepMgtRetentionDefinitionTypeUri,
                                                               GetType(ccdt.cmisTypeRM_RepMgtRetentionDefinitionType),
                                                               GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeRM_RepMgtRetentionDefinitionType)))},
         {typeSecondaryDefinitionTypeUri, New RealTypeCorrelation(typeSecondaryDefinitionTypeUri,
                                                                  GetType(ccdt.cmisTypeSecondaryDefinitionType),
                                                                  GetType(cjcdtg.cmisTypeDefinitionTypeConverter(Of ccdt.cmisTypeSecondaryDefinitionType)))}}

   End Class
End Namespace