'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34209
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

      '''<summary>
      '''  Sucht eine lokalisierte Zeichenfolge, die /***********************************************************************************************************************
      '''&apos;* Project: CmisObjectModelLibrary
      '''&apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      '''&apos;*
      '''&apos;* Contact: opensource&lt;at&gt;patorg.de
      '''&apos;* 
      '''&apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      '''&apos;*
      '''&apos;* This file is part of CmisObjectModelLibrary.
      '''&apos;* 
      '''&apos;* This library is free software; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      '''</summary>
      Friend ReadOnly Property cmis() As String
            Get
                Return ResourceManager.GetString("cmis", resourceCulture)
            End Get
        End Property

      '''<summary>
      '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
      '''&lt;!--
      '''&apos;* Project: CmisObjectModelLibrary
      '''&apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      '''&apos;*
      '''&apos;* Contact: opensource&lt;at&gt;patorg.de
      '''&apos;* 
      '''&apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      '''&apos;*
      '''&apos;* This file is part of CmisObjectModelLibrary.
      '''&apos;* 
      '''&apos;* This library is free software; you can redistribute it and/or
      '''&apos;* modify it under  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      '''</summary>
      Friend ReadOnly Property EmbeddedFrame() As String
            Get
                Return ResourceManager.GetString("EmbeddedFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        '''&lt;html&gt;
        '''	&lt;head&gt;
        '''		&lt;title&gt;&lt;/title&gt;
        '''	&lt;/head&gt;
        '''	&lt;body&gt;
        '''	
        '''	&lt;/body&gt;
        '''&lt;/html&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property EmptyPage() As String
            Get
                Return ResourceManager.GetString("EmptyPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The parameter &apos;{0}&apos; must not be null or empty. ähnelt.
        '''</summary>
        Friend ReadOnly Property InvalidArgument() As String
            Get
                Return ResourceManager.GetString("InvalidArgument", resourceCulture)
            End Get
        End Property

      '''<summary>
      '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
      '''&lt;!--
      '''&apos;* Project: CmisObjectModelLibrary
      '''&apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      '''&apos;*
      '''&apos;* Contact: opensource&lt;at&gt;patorg.de
      '''&apos;* 
      '''&apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      '''&apos;*
      '''&apos;* This file is part of CmisObjectModelLibrary.
      '''&apos;* 
      '''&apos;* This library is free software; you can redistribute it and/or
      '''&apos;* modify it under  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      '''</summary>
      Friend ReadOnly Property LoginPage() As String
            Get
                Return ResourceManager.GetString("LoginPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        '''&lt;html&gt;
        '''	&lt;head&gt;
        '''		&lt;title&gt;LoginRef&lt;/title&gt;
        '''	&lt;/head&gt;
        '''	&lt;body&gt;
        '''	    &lt;h1&gt;CmisObjectModel Repository Login&lt;/h1&gt;
        '''        &lt;div&gt;
        '''            &lt;p&gt;To provide your credentials for this CMIS repository follow the &lt;a href=&quot;LoginPage.htm&quot;&gt;link&lt;/a&gt;.&lt;/p&gt;
        '''        &lt;/div&gt;
        '''	&lt;/body&gt;
        '''&lt;/html&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property LoginRefPage() As String
            Get
                Return ResourceManager.GetString("LoginRefPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Method &apos;{0}&apos; is not supported. ähnelt.
        '''</summary>
        Friend ReadOnly Property NotSupported() As String
            Get
                Return ResourceManager.GetString("NotSupported", resourceCulture)
            End Get
        End Property

      '''<summary>
      '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
      '''&lt;!--
      '''&apos;* Project: CmisObjectModelLibrary
      '''&apos;* Copyright (c) 2014, Brügmann Software GmbH, Papenburg, All rights reserved
      '''&apos;*
      '''&apos;* Contact: opensource&lt;at&gt;patorg.de
      '''&apos;* 
      '''&apos;* CmisObjectModelLibrary is a VB.NET implementation of the Content Management Interoperability Services (CMIS) standard
      '''&apos;*
      '''&apos;* This file is part of CmisObjectModelLibrary.
      '''&apos;* 
      '''&apos;* This library is free software; you can redistribute it and/or
      '''&apos;* modify it under  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
      '''</summary>
      Friend ReadOnly Property RedirectPreviousPage() As String
            Get
                Return ResourceManager.GetString("RedirectPreviousPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No class in assembly found that matches the criteria: the class MUST {0} {1}, MUST have a public constructor which accepts the baseUri (System.Uri) parameter and MUST not be an abstract class. ähnelt.
        '''</summary>
        Friend ReadOnly Property ServicesImplNotFound() As String
            Get
                Return ResourceManager.GetString("ServicesImplNotFound", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
